version: '3'

services:
  traefik:
    image: traefik:v2.1
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro

  redis:
    image: redis:5-alpine
    restart: always

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  goshorty:
    image: ../
    restart: always
